version: 2
jobs:
   build-job:
     docker:
       - image: circleci/ruby:latest
     steps:
       - checkout
       - run: bundle install
       - run: bundle exec jekyll build
       - run: bundle exec htmlproofer ./_site --allow-hash-href --check-html --disable-external
       - run: echo "Build finished!"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job